name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt install sshpass -y && pip3 install waitress
      - name: Git pull and Deploy with Docker Compose
        run: |
          sshpass -p ${{ secrets.SERVER_PASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_NAME }} "cd Project/backend/anomaly-detection/PrimaryBackend && git pull && docker compose down ; docker compose up -d"
